### ISSUE TITLE
I have two helpful Suggestions for Improvement for the Ckeditor

### ISSUE THREAD

**Issue by ghost** [mecha-cms/extend.c-k-editor#1]
Hi @Tovic,

I thank you for this new extension, which I will still blog. I have two interesting suggestions for improvement.

- Upload images directly from your computer's hard drive
- SpellChecker for German and English users of Mecha CMS

Would it be possible to implement this?

Thanks and look forward to your early feedback.

**Comment by taufik-nurrohman** [comment]
The spellchecker (and other plugins that available in the full package) has been disabled for simplicity but the plugin still included in the extension. It is just not activated. I am still learning the CKEditor API and will consider to add the uploader once I have finished the asset manager page.
